---
runtime: shiny
output: html_document
---


```{r setup, include=FALSE, echo=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = FALSE)
#knitr::opts_chunk$set(message = FALSE)
```




```{r results='hide', message = FALSE, warning=FALSE, echo=FALSE}
library(shiny)
library(httr)
library(bit64)
library(jsonlite)
library(stringdist)
library(Hmisc)
library(data.table)
library(dplyr)
library(XML)
library(RCurl)
#library(tm)
source("Sno2Eng_shiny.R")

```

```{r  echo=FALSE, message = FALSE, warning = FALSE}

stylePanel <- "border:1px inset;border-color:#458cc3;background-color:ghostwhite;padding:0;"
styleText <- "overflow-y:scroll; height: 70px; font-family: monospace; font-size:12px; margin:0px;"
    
# Define UI for dataset viewer app ----
ui <- fluidPage(

  tags$head(tags$style(".shiny-output-error { visibility: hidden; } and .shiny-output-error:before { visibility: hidden; }")),
  
  # App title ----
  titlePanel("SNOMEDtxt: making SNOMED readable"),

  # Sidebar layout with a input and output definitions ----
  sidebarLayout(
      # Sidebar panel for inputs ----
      sidebarPanel(
          
          # Input: Selector for choosing dataset ----
          textInput(inputId = "searchterm", label = "Type a disease name:", placeholder="(ex: stroke)"),
          actionButton("do", "Get by name"),
          br(),
          br(),
          textInput(inputId = "snomedid", label = "Or a SNOMED concept ID:", placeholder="(ex. 13200003)"),
          actionButton("do2", "Get by ID")
      ),
      
      # Main panel for displaying outputs
      mainPanel(  style="overflow-y: auto;" ,
         h5("SNOMEDtxt verbalization of SNOMED"),
         wellPanel(style="border:1px inset;border-color:#458cc3;background-color:ghostwhite;padding:0;", 
                textOutput("sno2Eng")),
         h5("SNOMED original text"),
         wellPanel(style="border:1px inset;border-color:#458cc3;background-color:ghostwhite;padding:0;", 
                textOutput("snoOriginal")),
         h5("Reference (MedlinePlus)"),
         wellPanel(style="border:1px inset;border-color:#458cc3;background-color:ghostwhite;padding:0;", 
                textOutput("reference")),
         tags$style(type="text/css", "#sno2Eng{ overflow-y:scroll; height: 80px; font-family: monospace; font-size:12px; margin:0px;}"),
         tags$style(type="text/css", "#snoOriginal{ overflow-y:scroll; height: 80px; font-family: monospace; font-size:12px;}"),
         tags$style(type="text/css", "#reference{ overflow-y:scroll; height: 80px; font-family: monospace; font-size:12px;}")
      )
  )
)

# Define server logic to summarize and view selected dataset ----
server <- function(input, output) {
    
    v <- reactiveValues(data = NULL)
    v$sno2Eng <- "SNOMEDtxt will be displayed here"
    v$snoOr <- "Names and relationships listed in SNOMED will be concatenated as they are. "
    v$ref <- "Reference disease description from Medline Plus API will go here."
    
    observeEvent(input$do, {
        v$sno2Eng <- ""
        v$snoOr <- ""
        v$ref <- ""
        str <- trimws(input$searchterm)
        if(str != "") {
            e <- getSno2Eng(str)
            if(!is.null(e)) {
                id <- e$id
                t <- getSnoOriginal(id)
                v$sno2Eng <- e$story
                v$snoOr <- t$text
            } else {
                v$sno2Eng <- "Disease not found"
                v$snoOr <- "Disease not found"
            }
            m <- getMedline(str)
            if(!is.null(m)) {
                v$ref <- m
            } else {
                v$ref <- "Disease not found"
            }
        }
    })
        
    observeEvent(input$do2, {
        v$sno2Eng <- ""
        v$snoOr <- ""
        v$ref <- ""
        if (input$snomedid != "") {
            e <- getSno2EngByID(trimws(input$snomedid))
            if(!is.null(e)) {
                name <- e$name
                v$ref <- getMedline(name)
                v$sno2Eng <- e$story
            }
            else {
                 v$sno2Eng <- "Disease not found"
                 v$ref <- "Disease not found"
            }
            t <- getSnoOriginal(trimws(input$snomedid ))
            if(!is.null(t)) {
                v$snoOr <- t$text
            } else {
                v$snoOr <- "Disease not found"
            }
        }
    })

      output$sno2Eng <- renderText({
        if (is.null(v$sno2Eng)) return()
        unlist(v$sno2Eng)
      })
       
      output$snoOriginal <- renderText({
        if (is.null(v$snoOr)) return()
          v$snoOr
      })
    
       output$reference <- renderText({
        if (is.null(v$ref)) return()
          v$ref
      })

}

# Create Shiny app ----
shinyApp(ui = ui, server = server)
```
